### ISSUE TITLE
 Bug with Shift + Left-clicking in Trading Using Commercial Fish Basket

### ISSUE THREAD

**Issue by carrotwzx** [i493052739/TreasureSeas#1]
Description:
When I use the Commercial Fish Basket item, the normal behavior should be to trade by left-clicking. However, when I attempt to Shift + left-click to retrieve emerald blocks from the right side of the trade window, the emerald blocks are incorrectly placed in the left-side trade slot instead of the player's inventory. This issue leads to an unintended behavior where the emeralds are obtained without consuming the fish on the left side, essentially allowing the player to generate emeralds without completing the trade.

Steps to Reproduce:

Equip the Commercial Fish Basket item.
Initiate a trade with a villager (or relevant trading entity).
Offer fish on the left side of the trade window and attempt to trade for emerald blocks on the right side.
Shift + left-click on the emerald blocks in the right side to retrieve them.
Observe that the emerald blocks are placed in the left-side trade slot instead of the player's inventory, and the fish are not consumed.
Expected Behavior:
The emerald blocks should be transferred to the player's inventory when Shift + left-clicking, and the fish on the left side should be consumed as part of the trade.

Actual Behavior:
The emerald blocks are incorrectly placed in the left-side trade slot, and the fish are not consumed, allowing emeralds to be obtained without completing the trade.

Versions:

Mod Version: TreasureSeas-forge-1.18.2-1.0.0
Minecraft Version: 1.18.2

Additional Information:
No crash logs or error messages appear during this process.

Note: My English is not very good, so I used ChatGPT to help describe the issue more clearly. I apologize for any inconvenience caused. Thank you for your time and understanding!

**Comment by NattoCB** [comment]
Thanks mate! The fix would be built and released this weekend in version 1.0.1

**Comment by carrotwzx** [comment]
Thank you for your response! I'm really looking forward to the upcoming fix. Your mod is incredibly fun, and I've really enjoyed using it. We'll be using it on our server as well. Thank you for all your hard work!
