### ISSUE TITLE
通过钓鱼获得的附魔书无nbt标签

### ISSUE THREAD

**Issue by MisakaKuroko5** [i493052739/TreasureSeas#2]
Minecraft 1.18.2 Forge mod版本1.0.2

鱼之战斗一级钓鱼时获得的附魔书无nbt标签，仅为名字为附魔书的物品
![image](https://github.com/user-attachments/assets/bdcf5658-ebe3-4393-981b-a73ea04ce7ee)
使用钓竿如下
![image](https://github.com/user-attachments/assets/096d4658-8f32-44de-8b42-764810ff3b42)

**Comment by MisakaKuroko5** [comment]
还有一个不知道是兼容问题还是什么问题，在使用鱼篓时如果使用shift左键放入鱼会提示
![image](https://github.com/user-attachments/assets/3bc6acbc-be0f-4d96-b1cb-1c11ee3b2731)
但是用左键点击移动就没有问题

**Comment by NattoCB** [comment]
> Minecraft 1.18.2 Forge mod版本1.0.2
> 
> 鱼之战斗一级钓鱼时获得的附魔书无nbt标签，仅为名字为附魔书的物品

谢谢提供信息，这个问题会在 1.0.3 版本更新时一起修复，预计时间在下周末

> 还有一个不知道是兼容问题还是什么问题，在使用鱼篓时如果使用shift左键放入鱼会提示 [image] 但是用左键点击移动就没有问题

这个 GUI 的问题也会和 1.0.3 一起更新，优化交互体验

**Comment by MisakaKuroko5** [comment]
又玩了一段时间，不仅仅是附魔书，所有钓鱼获得的物品都没有ntb标签

**Comment by NattoCB** [comment]
> 又玩了一段时间，不仅仅是附魔书，所有钓鱼获得的物品都没有ntb标签

已修复，详情见 https://modrinth.com/mod/treasure-seas/changelog 1.0.3
